### ISSUE TITLE
TODO ко второму спринту

### ISSUE THREAD

**Issue by andreysdrv** [andreysdrv/middle.game.praktikum.yandex#16]
- [ ] привести структуру проекта к единому виду (scss modules, index.ts, assets...)
- [x] разбить на модули: базовые классы `api` и контроллеры
- [ ] доработать стили
- [ ] настроить конфиги для `eslint, prettier, typescript, husky, lintstaged`
- [ ] добавить правила для мерджа веток
- [ ] доработать шаблон для PR (название ПР: `feat/fix/format/style/test: название задачи решаемой в ПР`)

### [Номер задачи из linear: название задачи из linear]
[Что было сделано (можно по описанию задачи из linear или по сообщениям из коммитов]

### [Скриншоты или видео, если изменился UI]
